name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: ls
      run: ls 

    - uses: actions/checkout@v3
    
    - name: pwd2
      run: pwd
      
    - name: ls
      run: ls 
